Adkernel review
rubicon-project/prebid-server-java pull request #1000
Opened 2020-11-09 13:05 UTC by snahornyi

2020-11-13 13:52 UTC, DGarbar requested changes

2020-11-13 13:52 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/adkernel/AdkernelBidder.java
> +                .noneMatch(imp -> imp.size() > 0);
return pubToImps.values().stream().allMatch(CollectionUtils::isEmpty);

2020-11-13 13:52 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/adkernel/AdkernelBidder.java
> +    private static BidRequest createBidRequest(List<Imp> imps, BidRequest.BidRequestBuilder requestBuilder,
```
    private static BidRequest createBidRequest(List<Imp> imps,
                                               BidRequest.BidRequestBuilder requestBuilder,
                                               Site site,
                                               App app)
```

2020-11-13 13:52 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/adkernel/AdkernelBidderTest.java
> +                        && error.getMessage().startsWith("Invalid imp id=123. Expected imp.banner or imp.vide"));
I don't see why it is better (in all cases)

2020-11-16 13:07 UTC, DGarbar approved these changes

2020-11-17 14:33 UTC, rpanchyk reviewed
LGTM, just merge master.

2020-11-18 13:26 UTC, rpanchyk approved these changes

2020-11-18 13:27 UTC, merged