Add implementation and tests of BeintooBidder
rubicon-project/prebid-server-java pull request #813
Opened 2020-07-15 14:52 UTC by AndriyPavlyuk

2020-09-16 13:28 UTC, DGarbar requested changes

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +            errors.add(BidderError.badInput("No valid impressions in the bid request"));
Use special method for single error

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +        final List<BidderError> errors = new ArrayList<>();
declare near usage

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +        return site != null && StringUtils.isNotBlank(site.getPage()) && site.getPage()
redundant /n

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +            tagidNumber = Integer.parseInt(extImpBeintoo.getTagId());
You can replace with StringUtils.isNumeric and then parse

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +                .bidfloor(bidfloor)
also check if >0

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +        final Imp.ImpBuilder impBuilder = imp.toBuilder()
Create object in the end of the method.

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +        if (StringUtils.isBlank(stringBidfloor)) {
Refactor this to be like 
```
stringBidfloor = extImpBeintoo.getBidFloor();
StringUtils.isBlank(stringBidfloor) ? null : new BigDecimal(stringBidfloor)

bidfloor(bidfloor.compareTo(BigDecimal.ZERO) > 0 ? bidfloor : imp.getBidfloor())
```

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +            if (originalFormat == null || originalFormat.isEmpty()) {
CollectionUtils

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +            bannerBuilder.w(firstFormat.getW());
final

2020-09-16 13:28 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +                .map(bid -> BidderBid.of(modifyBid(bid), BidType.banner, DEFAULT_BID_CURRENCY))
just use another `.map` instead of method in `.of`

2020-09-18 08:25 UTC, DGarbar requested changes
`  private static final String DEFAULT_BID_CURRENCY = "USD";` redundant

2020-09-18 08:25 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +import org.springframework.util.CollectionUtils;
use class form `apache`

2020-09-18 08:25 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/beintoo/BeintooBidder.java
> +        final List<BidderError> errors = new ArrayList<>();
just return emptyList

2020-09-18 09:29 UTC, DGarbar approved these changes

2020-09-22 12:18 UTC, rpanchyk approved these changes

2020-09-22 12:35 UTC, merged