Update currency rates endpoint URL and response body
rubicon-project/prebid-server-java pull request #820
Opened 2020-07-20 10:31 UTC by schernysh

2020-09-01 12:39 UTC, DGarbar requested changes

2020-09-01 12:39 UTC, DGarbar commented on src/test/java/org/prebid/server/it/ApplicationTest.java
>      public void currencyRatesHandlerShouldRespondWithLastUpdateDate() {
Probably need to change name

2020-09-01 13:04 UTC, DGarbar approved these changes

2020-10-08 15:42 UTC, rpanchyk approved these changes

2020-10-09 14:39 UTC, merged