Add Yeidlab Bidder and tests
rubicon-project/prebid-server-java pull request #828
Opened 2020-07-28 10:48 UTC by AndriyPavlyuk

For passing validation tests it was harcoded timestamp and number of weeks in year.

final String timestamp = isDebugEnabled(request)
? "200000"
: String.valueOf(Instant.now().getEpochSecond());

final int weekNumber = isDebugEnabled(bidRequest)
? 35
: Calendar.getInstance().get(Calendar.WEEK_OF_YEAR);

2020-09-15 14:02 UTC, DGarbar requested changes

2020-09-15 14:02 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java
> +        Map<String, String> targeting = new HashMap<>();
final

2020-09-15 14:02 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java
> +                                ExtImpYieldlab.of("1", "2", "adSize", targeting, "extId"))))
Lets use builder when we have more than 3 parameters

2020-09-22 10:53 UTC, DGarbar requested changes

2020-09-22 10:53 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
> +        imps.forEach(imp -> extImps.add(parseImpExt(imp)));
use .map()

2020-09-22 11:28 UTC, DGarbar approved these changes

2020-09-22 13:17 UTC, rpanchyk approved these changes

2020-09-22 13:17 UTC, merged