Support pubmatic video duration and primary category
rubicon-project/prebid-server-java pull request #849
Opened 2020-08-07 14:33 UTC by BraslavskiyAndrey

2020-08-31 13:14 UTC, DGarbar requested changes

2020-08-31 13:14 UTC, DGarbar commented on src/main/java/org/prebid/server/auction/BidResponseCreator.java
> +    private ExtBidPrebidVideo getExtBidPrebidVideo(ObjectNode bidExt) {
Lets move this method to the end of the file, to match method workflow order

2020-09-07 12:37 UTC, DGarbar submitted a review, later dismissed

2020-09-18 08:30 UTC, rpanchyk approved these changes

2020-09-18 08:32 UTC, merged