Add DmxBidder and tests
rubicon-project/prebid-server-java pull request #859
Opened 2020-08-12 21:24 UTC by AndriyPavlyuk

Updated dmx endpoint in dmx.yaml due to HB-9356

2020-09-16 12:15 UTC, DGarbar requested changes

2020-09-16 12:15 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +                    final Bid updatedBid = bid.toBuilder().adm(adm).build();
```
                    final Bid updatedBid = bidType == BidType.video 
                            ? bid.toBuilder().adm(getAdm(bid)).build()
                            : bid;
```

2020-09-16 12:15 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/dmx/DmxBidderTest.java
> +                .site(Site.builder().build())
this line is covers NPE which is BUG. Remove from ALL tests

2020-09-16 12:15 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/dmx/DmxBidderTest.java
> +                                        ExtImpDmx.of("tagId", "dmxId", "memberId", "publisherId",
use builder when there are more then 3 parrameters

2020-09-16 12:15 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/dmx/DmxBidderTest.java
> +                .containsOnly(tuple("id", "dmxId", mapper.valueToTree(ExtPrebid.of(null,
extract long variables for code clearance

2020-09-16 12:15 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/dmx/DmxBidderTest.java
> +                .extracting(Imp::getId, Imp::getTagid, Imp::getExt, Imp :: getSecure)
redundant spaces

2020-09-19 10:35 UTC, AndriyPavlyuk commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +        if (site.getPublisher() != null) {
This check will be redundant

2020-09-19 10:35 UTC, AndriyPavlyuk commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +        final Publisher publisher = site.getPublisher();
site.getPublisher() != null this check also site!=null

2020-09-19 10:57 UTC, AndriyPavlyuk commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +        if (site.getPublisher() != null) {
Intellijent Idea propose to siplify and remove this check

2020-09-22 11:27 UTC, DGarbar submitted a review, later dismissed

2020-09-22 11:27 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +            updatedPublisherId = StringUtils.isBlank(publisherId)
can be in 1 line

2020-09-22 11:27 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +            for (Imp imp : request.getImp()) {
try need to be inside loop. 
Just create two try catch blocks for extraction of publisher and for imps

2020-09-22 11:27 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +                request.toBuilder()
you can do smth like this 
updatedPublisher = site.Publisher == null ? Publisher.builder().id(updatedPublisherId).build() : publisher.toBuilder().id(updatedPublisherId).build()

2020-09-22 11:27 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +    private void checkIfHasId(boolean anyHasId) {
Not that. 
I mean that we can extract **ALL** related logic to this variable to separate method

2020-09-22 11:27 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/dmx/DmxBidder.java
> +        return updatedImp != null && StringUtils.isBlank(updatedImp.getTagid()) && StringUtils.isBlank(imp.getTagid())
just return upratedImp

2020-09-23 09:47 UTC, DGarbar submitted a review, later dismissed

2020-09-23 10:41 UTC, rpanchyk approved these changes

2020-09-23 10:50 UTC, merged