consumable: Correct width and height reported in response.
rubicon-project/prebid-server-java pull request #880
Opened 2020-08-26 21:33 UTC by djcsdy

This PR corresponds to Prebid/prebid-server#1459.

Corrects the width and height specified in the bid response.

After this change, Prebid Server uses the width and height specified in the **bid response** from Consumable.

Previously, Prebid Server would reuse the width and height specified in the **bid request**. That older behaviour was ported from an older version of the prebid.js adapter but is no longer valid.

I am submitting this PR on behalf of Consumable, cc @naffis.

2020-08-27 12:35 UTC, DGarbar requested changes

2020-08-27 12:35 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/consumable/model/ConsumableDecision.java
> +    @JsonProperty("width")
redundant. Pls remove

2020-08-27 12:35 UTC, DGarbar commented on src/main/java/org/prebid/server/bidder/consumable/model/ConsumableDecision.java
> +    @JsonProperty("height")
redundant. Pls remove

2020-08-27 12:35 UTC, DGarbar commented on src/test/java/org/prebid/server/bidder/consumable/ConsumableBidderTest.java
> +                        .width(120).height(90)
You used same values, which we used in `Banner.format[0]` so for better understanding, lets use diffrent one.

(Also correct line 306)

2020-09-01 22:18 UTC, djcsdy commented
I've made the requested changes.

2020-09-02 14:40 UTC, DGarbar approved these changes

2020-09-18 11:37 UTC, merged