Optionally read IFA value and add it the the request url (Adhese)
rubicon-project/prebid-server-java pull request #989
Opened 2020-11-02 15:25 UTC by sander-adhese

Next to the referer and the consent string we also want to send the Device IFA (if present) to our Adhese endpoint - if present.

2020-11-02 17:29 UTC, snahornyi commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +                : "";
Minor. Maybe one line will be better
` return device != null && StringUtils.isNotBlank(device.getIfa())
                ? String.format("%s%s", QUERY_PARAMETER_IFA, device.getIfa())
                : "";`

2020-11-02 17:33 UTC, snahornyi commented on src/test/java/org/prebid/server/bidder/adhese/AdheseBidderTest.java
> +                        .build())
Minor. We prefer to use builder in separate lines only in case if single line is more then checkstyle line length rule constant.

2020-11-02 17:35 UTC, snahornyi submitted a review, later dismissed

2020-11-17 12:20 UTC, rpanchyk requested changes

2020-11-17 12:20 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +        return site != null && StringUtils.isNotBlank(site.getPage())
Seems separate variable was better choice.

2020-11-17 12:20 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +        return device != null && StringUtils.isNotBlank(device.getIfa())
i'd recommend `ifa` as separate variable.

2020-11-17 12:20 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +                ? String.format("%s%s", QUERY_PARAMETER_IFA, device.getIfa()) : "";
Should we make url-encoding here?

2020-11-17 12:20 UTC, rpanchyk commented on src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
> +    private static final String QUERY_PARAMETER_IFA = "/xz";
Minor. Usually most valuable thing can placed at first position, like `IFA_QUERY_PARAMETER`.
If you're ok with it, pls check for other fields.

2020-11-18 09:32 UTC, rpanchyk approved these changes

2020-11-18 09:34 UTC, merged